export const data=[{
    id :1,
    image:"kalam.jpg",
    name:"ANDHRA_PRADESH",
    img1 :"kalam.jpg",
    desc :"Kalamkari means, “pen-art”. Kalamkari paintings are either hand painted or block printed on cotton fabric. This art form flourished under the rule",
},
{
    id:2,
    image:"cc.jpg",
    name :"BIHAR",
    img1:"cc.jpg",
    desc:"Madhubani paintings are among the most famous paintings in the world. This popular art of the Mithila region expresses 56creativity",
},
{
    id:3,
    image:"dd.jpg",
    name :"HIMACHAL_PRADESH",
    img1:"dd.jpg",
    desc:"The Kangra paintings are an art form of Kangra, India. It is said that the craft was born in the 17th century",

},
{
    id:4,
    image:"download.jpg",
    name :"JHARKHAND",
    img1:"download.jpg",
    desc:"The Jadopatia painting of Jharkhand is a type of folk art that has been practiced in the Indian state of Jharkhand for centuries.",
},
{
    id:5,
    image:"hd.jpg",
    name :"KERALA.",
    img1:"hd.jpg",
    desc:"Kalamezhuthu is a traditional art form that originated in Kerala. The art form uses the patterns of rice flour paste and water colours on a cloth to create elaborate paintings.v",
},
{
    id:6,
    image:"md.jpg",
    name :"MADHYA_PRADESH",
    img1:"md.jpg",
    desc:"Term “Chitrakathi” comes from two words: “chitra” meaning picture and “katha” meaning story. A Chitrakathi is someone who tells stories, with a visual aid.",
},
{
    id:7,
    image:"maharastra.jpg",
    name :"MAHARASTRA",
    img1:"maharastra.jpg",
    desc:"Gond painting has been practiced by the Gond tribe of Madhya Pradesh, India.",
},
{
    id:8,
    image:"jj1.jpg",
    name :"RAJASTHAN",
    img1:"jj1.jpg",
    desc:"Rajasthani paintings are divided into different schools, one of which is the Kishangarh School of Art. ",
},
{
    id:9,
    image:"download.jpg",
    name :"TAMIL_NAD",
    img1:"download.jpg",
    desc:"A Kolam is a geometrical line drawing made up of straight lines, curves and loops, constructed around a dot grid pattern.",
},
{
    id:10,
    image:"rj.jpg",
    name :"WEST_BENGAL",
    img1:"rj.jpg",
    desc:"Dokra Art (also called Dhokra) named after Dhokras tribe, a nomadic group that extends ",
}]